# Generated by Django 3.2.7 on 2021-09-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='email',
            field=models.CharField(default='null@email.com', max_length=100),
        ),
    ]
